[package]
name = "mime-plz"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5"
serde = { workspace = true }

[build-dependencies]
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "mybench"
harness = false
