[package]
name = "buffer-plz"
version = "0.0.2"
authors = ["darkseid", "sytten <emile@caido.io>"]
description = "Buffer for the ParsePlz ecosystem"
repository = "https://github.com/parseplz/primitives"
license = "MIT"
edition = "2024"

[dependencies]
bytes = { workspace = true }
