name: Run CI

on:
  pull_request:
  push:
    branches:
      - 'main'

concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Caching
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/master' }}
          cache-provider: "github"

      - name: Run linter
        uses: giraffate/clippy-action@871cc4173f2594435c7ea6b0bce499cf6c2164a1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --all-features -- -D warnings
          reporter: github-pr-review

      - name: Run formatter
        run: cargo fmt --all -- --check

  test:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4
      - name: Caching
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/master' }}
          cache-provider: "github"

      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest

      - name: Test with latest nextest release
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run
